language: go

go:
 - 1.14.x
 - master

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

notifications:
 email: false

before_install:
 - go get github.com/kshedden/formula

after_success:
  - bash <(curl -s https://codecov.io/bash)

